### PR TITLE
Make inviting individual users or a collection of users easier

### PR DESCRIPTION
**Pull request by jessepollak**

### CODE REVIEW

**Comment by jessepollak** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;q0jmC0gQ&#x2F;24-add-per-user-invites-and-better-invite-success-error-messages"> Add per-user invites and better invite success&#x2F;error messages</a>

**Comment by jessepollak** [comment]
Some screenshots of how this looks and feels.

### Bulk user invitations on the User page.

screenshot 2016-02-10 09 05 08

### Callout in Clef settings to invite users
screenshot 2016-02-10 10 09 24

**Comment by jessepollak** [comment]
Note, this fixes #124.

**Comment by lolux** [comment]
So nice

**Pull request merged**
