### PR TITLE
Add option for initializing state on every page

### PR DESCRIPTION
**Pull request by jessepollak**

### CODE REVIEW

**Comment by jessepollak** [comment]
@lolux I pushed the migration from previous versions, bumped the version to `2.6.0` and pushed `v2.6.0-beta1` [here](https://github.com/clef/clef-wordpress/releases/tag/v2.6.0-beta1).

**Comment by lolux** [comment]
@jessepollak most excellent, thank you.

The third-party beta testing and my own testing is nearly complete. We have a green light from Pantheon already. I'll ping back here once the remaining tests have finished.

**Comment by jessepollak** [comment]
woot - keep me updated!

On Wed, Jun 29, 2016 at 2:03 PM, lolux <notifications@github.com> wrote:

> @jessepollak <https://github.com/jessepollak> most excellent, thank you.
>
> The third-party beta testing and my own testing is nearly complete. We
> have a green light from Pantheon already. I'll ping back here once the
> remaining tests have finished.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/clef/clef-wordpress/pull/255#issuecomment-229488167>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABDA4V0RU3HXp6SPG85F3Oato1cZt4iwks5qQt20gaJpZM4I_fBv>
> .
>



-- 
Jesse Pollak
CPO at Clef
@jessepollak <https://twitter.com/jessepollak>

**Comment by jessepollak** [comment]
Thanks for all your hard work on this @lolux!

**Pull request merged**
