### PR TITLE
Update readme for 2.3.1

### PR DESCRIPTION
**Pull request by lolux**
@jessepollak things to note/tweak on your end besides cherry-picking the text refresh suggestions:

1. Tag no. (line 7)
1. Release date and log items (lines 137ff.)

### CODE REVIEW

**Comment by lolux** [comment]
Refreshed screenshots . . .
screenshot-1
screenshot-2
screenshot-3
screenshot-4

**Comment by jessepollak** [comment]
Looks great to me, want me to merge it in?

**Comment by lolux** [comment]
@jessepollak It's ready . . . though we still need to remove password disabling (changelog item)

**Comment by jessepollak** [comment]
OK, do you feel confident doing that or want me to take a look? Should be pretty straightforward.

**Pull request merged**
